pipeline {
    agent  any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Build ') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                sh 'pwd'
            }
        }
        // stage('Build Image') {
        //     steps {
        //         sh 'docker build -t app-node .'
        //         sh 'docker images'
        //     }
        // }
    }
}
