pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Build ') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t app-node .'
                sh 'docker images'
            }
        }
    }
}
